{% set python_min = "3.10" %}
{% set name = "flashgeotext" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e17623a88e41dacea52b34b8af0163dccf39c2053a4979e2b2011d7c4113aff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flashtext >=2.7,<3.0
    - loguru >=0.5.3
    - pip
    - poetry-core >=1.0.0,<2.0.0
    - pydantic >=2.7.1,<3.0
    - python {{ python_min }}
  run:
    - flashtext >=2.7.0,<3.0.0
    - loguru >=0.7.3,<0.8.0
    - pydantic >=2.10.5,<3.0.0
    - python >={{ python_min }}

test:
  imports:
    - flashgeotext
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/iwpnd/flashgeotext/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract and count countries and cities (+their synonyms) from text
  doc_url: https://github.com/iwpnd/flashgeotext
  dev_url: https://github.com/iwpnd/flashgeotext

extra:
  recipe-maintainers:
    - iwpnd
    - francbartoli
